name: ascribe
favicon: null
layout_spectrum: 0.7453
typography_spectrum: 0.85557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6939806649461389
  lightness: 0.42647787230089307
  saturation: 0.40707675903104246
  rhythmicContrast: 0.6610941577237099
purpose: []
